### PR TITLE
Update tracebox to 0.4.4 and create README.md with the steps to add tracebox feed

### PR DESCRIPTION
**Pull request by arinc9**
This pull request updates tracebox to 0.4.4 and creates README.md with the steps necessary to add and install the tracebox feed.

I also suggest to change the repository name to tracebox-openwrt to not cause confusion between the OpenWrt SDK and this feed.

### CODE REVIEW

**Comment by oliviertilmans** [comment]
Hi @arinc9,

Thanks for the update!

> I also suggest to change the repository name to tracebox-openwrt to not cause confusion between the OpenWrt SDK and this feed.

Does this mean that the steps outlined in your README.md are not working? If so, I'll change the repo name (and you can update the feed snippet).

**Comment by arinc9** [comment]
Hey @oliviertilmans. It does work as is but, it'd be a better idea to change the repo name. Then I can update the README.md to reflect that.

**Comment by oliviertilmans** [comment]
> Hey @oliviertilmans. It does work as is but, it'd be a better idea to change the repo name. Then I can update the README.md to reflect that.

Done! Let me know when to merge.

**Comment by arinc9** [comment]
Ready to merge! @oliviertilmans

**Comment by oliviertilmans** [comment]
Thanks!

**Pull request merged**
